### ISSUE TITLE
 Will TimeMachine fail?

### ISSUE THREAD

**Issue by Dr-wgy** [arextest/arex-agent-java#182]
https://github.com/alibaba/jvm-sandbox/releases/tag/1.4.0
https://github.com/alibaba/jvm-sandbox/wiki/USER-FAQ#%E6%B2%99%E7%AE%B1%E5%A6%82%E4%BD%95%E5%A2%9E%E5%BC%BAjvm%E5%9B%BA%E6%9C%89%E5%87%BD%E6%95%B0

**Comment by mr3** [comment]
Yep, `arex-agent` also encounters the same problem. 

For program execution performance, we do not recommend  disable `Intrinsic` by default.

Instead of enhancing `java.lang.System::currentTimeMillis`, we choose to enchance the following methods.

```
java.time.Instant
java.time.LocalDate
java.time.LocalTime
java.time.LocalDateTime
java.util.Date
java.util.Calendar
org.joda.time.DateTimeUtils
java.time.ZonedDateTime
```
[Click me see the source code: TimeMachineModuleInstrumentation.java](https://github.com/arextest/arex-agent-java/blob/main/arex-instrumentation/time-machine/arex-time-machine/src/main/java/io/arex/inst/time/TimeMachineModuleInstrumentation.java)

**Comment by lucas-myx** [comment]
@Dr-wgy 
If you use the `java. lang. System#currentTimeMillis` method in your project, you can also solve this problem by adding dynamic classes on the configuration page: (Settings->Record->Advanced->Dynamic Classes)
<img width="1123" alt="currenttimemills-config" src="https://github.com/arextest/arex-agent-java/assets/24931064/1a813a98-06bd-490f-97b0-896f89d9e669">

The principle is that `arex-agent` replaces the parts of your `.Class` that use `java. lang. System#currentTimeMillis` with arex's own `currentTimeMillis` method, thus avoiding the problem of directly modifying the `java. lang. System#currentTimeMillis` method and being optimized by JIT to be ineffective.

refer to: 
[DynamicClassInstrumentation#replaceMethod](https://github.com/arextest/arex-agent-java/blob/main/arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/DynamicClassInstrumentation.java)

**Comment by mr3** [comment]
@Dr-wgy Please reopen this issue if you have further questions.

**Comment by Dr-wgy** [comment]
> [@Dr-wgy](https://github.com/Dr-wgy) If you use the `java. lang. System#currentTimeMillis` method in your project, you can also solve this problem by adding dynamic classes on the configuration page: (Settings->Record->Advanced->Dynamic Classes) <img alt="currenttimemills-config" width="1123" src="https://private-user-images.githubusercontent.com/24931064/242827612-1a813a98-06bd-490f-97b0-896f89d9e669.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQxNjc2NTUsIm5iZiI6MTc0NDE2NzM1NSwicGF0aCI6Ii8yNDkzMTA2NC8yNDI4Mjc2MTItMWE4MTNhOTgtMDZiZC00OTBmLTk3YjAtODk2Zjg5ZDllNjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDA5VDAyNTU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZWIwNjJkNGU4ZjI1MDgwNDEwNzE1MDE2NGI4MTY2M2JjYzE2NDRiYjcwMmRjNzEyMjc5N2VhNGVkNzczMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E-SyYHFZCVHJgz-9owDWmOdMSzY7GjQ79mX_WuiduZk">
> 
> The principle is that `arex-agent` replaces the parts of your `.Class` that use `java. lang. System#currentTimeMillis` with arex's own `currentTimeMillis` method, thus avoiding the problem of directly modifying the `java. lang. System#currentTimeMillis` method and being optimized by JIT to be ineffective.
> 
> refer to: [DynamicClassInstrumentation#replaceMethod](https://github.com/arextest/arex-agent-java/blob/main/arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/DynamicClassInstrumentation.java)


If our project uses java in many places. Lang. System#currentTimeMillis Using dynamic classes is not very troublesome 
Is it possible to support recording in one of the following packages 
For example, com.xxxxCompany 
if we use System#currentTimeMillis  under the package com.xxxxCompany, it will Replaced by io.arex.inst.dynamic.ReplaceMethodHelper currentTimeMillis 
it isMore convenience
