### ISSUE TITLE
期望增加只回放不录制功能

### ISSUE THREAD

**Issue by tomzhang-liang** [arextest/arex-agent-java#229]
我的使用场景是UAT环境录制，测试环境回放，两方都需要起agent，测试环境在回放的时候还要重新启动AGENT，并且回放期间不能有任何操作，有操作的话就会导致数据被录进去，从而使测试和UAT环境的录制数据产生冲突。期望增加只回放不录制功能，降低回放时误录进数据的错误概率。

**Comment by mr3** [comment]
@tomzhang-liang 感谢反馈, 我们会尽快支持这个需求.
