### ISSUE TITLE
你好，请问高并发时候，出现的问题，有好的办法使用此工具复现吗？

### ISSUE THREAD

**Issue by cfy3133** [arextest/arex-agent-java#231]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lucas-myx** [comment]
@cfy3133  Arex在回放时默认是并行操作的，回放的过程相当于做了一次压测，而且是生产真实的录制流量，所以Arex是天然支持这种场景的，你也可以通过修改回放时的QPS来调整：
![arex_replay_qps](https://github.com/arextest/arex-agent-java/assets/24931064/c7125bd5-e21c-4ab9-875e-6b2784aac595)

**Comment by cfy3133** [comment]
好的，谢谢回复，请问怎么样debug调试代码？

**Comment by mengqcc** [comment]
在回放报告里把用例保存下来(保存在Collection)，本地启动应用，加载agent，然后就可以本地debug了

**Comment by mr3** [comment]
@cfy3133 感谢反馈，这个issue先关闭了，后续有任何问题可以随打开或者新建issue。
