### ISSUE TITLE
建议读取arex.agent.conf配置信息增加strip函数处理，增强容错性

### ISSUE THREAD

**Issue by imath60** [arextest/arex-agent-java#24]
### 复现步骤：
1、arex.agent.conf配置如下
arex.service.name=your-service-spring-petclinic
arex.storage.service.host=10.252.208.27:8093【有空格】
arex.config.service.host=10.252.208.27:8091【有空格】
2、启动服务
### 期望结果：
服务正常启动
### 实际结果：
因存在空格导致接口ip:hist【有空格】/path找不到
### 优化建议：
读取配置后，使用strip函数处理，增强代码容错性

**Comment by mr3** [comment]
Fixed in PR: #25
