### ISSUE TITLE
动态类mock支持的鉴权组件不包含jedis 2.9.0版本

### ISSUE THREAD

**Issue by liuxiaoer99** [arextest/arex-agent-java#252]
使用场景：
对于登录失效时的回放，需要配置动态类mock鉴权方法，其中涉及jedis。
jedis版本：2.9.0
例如使用到的类名和方法名：redis.clients.jedis.JedisCluster 类的ttl、hget、expire方法。

**Comment by mr3** [comment]
@liuxiaoer99 感谢你的反馈，我们查看确认一下。

**Comment by mr3** [comment]
@DanLi39 PTAL

**Comment by DanLi39** [comment]
> 使用场景： 对于登录失效时的回放，需要配置动态类mock鉴权方法，其中涉及jedis。 jedis版本：2.9.0 例如使用到的类名和方法名：redis.clients.jedis.JedisCluster 类的ttl、hget、expire方法。

We tried to reproduce this situation in the local environment, but found that data recording and replay of JedisCluster operations are supported. So we need you to describe the usage scenario in more detail and provide more information to help us troubleshoot, such as reference dependencies, calling methods , dynamic class configuration, etc.

**Comment by liuxiaoer99** [comment]
十分感谢您的排查及回复，如果是支持JedisCluster操作数据的录制和回放的，那应该就没有其他问题了。因为我们后面使用了其他方式处理token失效的问题，没有配置涉及jedis该版本的动态类，所以目前也不能提供更多的调用方法、使用场景等。谢谢。

**Comment by mr3** [comment]
@liuxiaoer99 Thank you for posting in the AREX community! If you have more infomation, please reopen and add it.
