### ISSUE TITLE
登录鉴权：对无法mock的鉴权框架，提供接口配置获取cookies (录制回放和常规请求)

### ISSUE THREAD

**Issue by zhouxihong1** [arextest/arex-agent-java#253]
**1. 需求描述**

**范围定义：**
针对于市面上所有无法mock鉴权的第三方框架或自定义框架

**需求能力：**
提供一种通用的登录鉴权接口能力，增加配置【接口url、入参json】，从而获取response返回鉴权：cookies等

**需求特性：**
以供在**录制回放**，和**固化用例的常规测试**时，能够直接注入最真实的请求，具有兼容所有mock和非mock的鉴权框架的特性，并能支持在不具备agent端的服务器上回放数据

**2. 初步考虑的解决方案**
2.1 设计开关配置

2.2 增加输入配置项，形如：

```python
# 登录接口通用请求: 
https://xxx:xxx/xxxx
# 入参输入示例:
{
"username": "admin",
"password": "加密的密钥串"
}

# 出参:
{
"code": xxxx
}
此时arex获取返回的cookies
```

上面的接口输入，入参输入只是一个示例，让用户配置即可，arex只做发送请求与处理response的鉴权信息
获取cookies和定义的鉴权信息后，自动添加在**录制回放**，和**固化用例的常规测试**时

**Comment by lucas-myx** [comment]
@zhouxihong1 
谢谢你的建议，这个方案是可行的，不过如果真的要做可能会参考dubbo自定义协议回放的实现。

其实现在主要的问题是需要用户参与二次开发，有一定的接入成本，且外部环境无法我们无法保证生产和测试的用户名、token是互通的，这里会涉及很多不可控因素，我们内部还需要评估下方案。

目前来说最简单的方案就是通过配置动态类的方式解决鉴权登录问题（AREX Agent新版本已支持void方法的mock了）

**Comment by mr3** [comment]
@zhouxihong1 Thank you for posting in the AREX community! If you have more infomation, please reopen and add it.
