### ISSUE TITLE
通过指定arex.agent.conf配置文件时 arex.storage.model未生效

### ISSUE THREAD

**Issue by imath60** [arextest/arex-agent-java#28]
# 复现步骤：
 1、如图所示设置arex.agent.conf文件，指定arex.storage.model=local
![image](https://user-images.githubusercontent.com/6263682/181001164-fb60cf67-d380-4da5-8ec3-222d904eaed7.png)
2、启动服务
```
java -javaagent:./arex-agent-0.0.1.jar -Darex.config.path=./arex.agent.conf -jar spring-petclinic-2.7.0-SNAPSHOT.jar
```
# 期望结果：
mode类型为local
# 实际结果：
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/6263682/181001196-d8d7f906-e77f-4539-8040-a89198994d76.png">

# 临时解决方法：
在命令行 增加 arex.stroage.model=local
```
java -javaagent:./arex-agent-0.0.1.jar -Darex.storage.model=local -Darex.config.path=./arex.agent.conf -jar spring-petclinic-2.7.0-SNAPSHOT.jar
```

**Comment by lucas-myx** [comment]
Thank you for your feedback! It has been repaired. 
In addition, please note the **README** has been updated `arex.storage.mode=local` (misspelling a word)
