### ISSUE TITLE
兼容Redisson3.20.1的版本

### ISSUE THREAD

**Issue by jcl-jcl** [arextest/arex-agent-java#284]
现在agengt不兼容Redisson3.20.1的版本，会报错 java.lang.NoSuchMethodError: org.redisson.connection.ConnectionManager.getConfig()Lorg/redisson/config/MasterSlaveServersConfig;

**Comment by DanLi39** [comment]
> 现在agent不兼容Redisson3.20.1的版本，会报错 java.lang.NoSuchMethodError: org.redisson.connection.ConnectionManager.getConfig()Lorg/redisson/config/MasterSlaveServersConfig;

The 3.20.1 version of redisson is already compatible, please pull the latest code to try.
