### ISSUE TITLE
k8s内被录制服务重新启动时agent没有正常加载

### ISSUE THREAD

**Issue by haolf000** [arextest/arex-agent-java#287]
**Bug description**
k8s中服务重新部署后agent没有正常加载

**Steps to reproduce**
1. 服务和agent开始正常工作
![38df5930-d56c-4132-a307-c93f2ef69f00](https://github.com/arextest/arex-agent-java/assets/49505146/f003b07e-d6f1-495b-b0e0-30f239ae5e9e)

2. 重新部署服务，新的agent没有启动成功
![3682d794-da33-4b91-8999-c10f2c44f364](https://github.com/arextest/arex-agent-java/assets/49505146/e90cb77a-2688-4d02-b3f2-29e27053c82e)
![528f3241-3146-42ac-af66-168729ec6526](https://github.com/arextest/arex-agent-java/assets/49505146/3285a9d5-e214-4437-a09e-6769820b3772)

3. 旧的agent发出shutdown信号关闭杀掉了旧的agent
odin-backend-56c49f84b7-vn52d app [arex-agent-shutdown-hook] INFO io.arex.foundation.services.ConfigService - [AREX] Agent shutdown, stop working now.
[AREX] Report agent status, previous lastModified: Mon, 11 Sep 2023 09:13:45 GMT, lastModified: 0. request: {"appId":"odin-backend","host":"[10.13.26.171](http://10.13.26.171/)","agentStatus":"SHUTDOWN","currentRate":"0","decelerateCode":0}, responseBody: demo agentStatus body, responseStatusCode: 200

![55272f1e-e074-4253-94c8-9d022476587b](https://github.com/arextest/arex-agent-java/assets/49505146/50752e42-6dc1-4bb3-a1f9-e8ad37d8b44a)

**Expected behavior**
新的agent随新pod启动正常加载，旧的agent随pod被shutdown

**What went wrong?**
新的agent没有起来，旧的agent也被shutdown掉了

**Environment**
k8s，docker，springboot，
Compiler: openjdk 8
arex-agent-java: 0.3.10（last commit: d33428629b4599819d58a913a0fe551bbbfb79f2）

**Comment by haolf000** [comment]
odin-backend-7d7cf6db4f-z2kth app [main] INFO io.arex.foundation.services.ConfigService - [AREX] Report agent status, previous lastModified: null, lastModified: Mon, 11 Sep 2023 09:13:45 GMT. request: {"appId":"odin-backend","host":"10.13.25.96","agentStatus":"UN_START","currentRate":"1","decelerateCode":0}, responseBody: demo agentStatus body, responseStatusCode: 200
odin-backend-7d7cf6db4f-z2kth app [main] WARN io.arex.agent.instrumentation.BaseAgentInstaller - [AREX] Agent would not install due to response [targetAddress] is not match.  看着像是ip变化导致无法load agent

**Comment by lucas-myx** [comment]
@haolf000 
感谢反馈，arex预计在10月中旬会上线shutdown的功能，在服务下线时通知arex-storage，到时会修复这个，
目前的话你可以通过点击页面上的`delete`, 再重启应用即可。
