### ISSUE TITLE
Content-Type为form-data录制不到body 

### ISSUE THREAD

**Issue by ZHFlys** [arextest/arex-agent-java#310]
如果Content-Type为form-data 参数默认录制不到 body为空 agent的CachedBodyRequestWrapperV3#isFormPost加上这个判断body

![image](https://github.com/arextest/arex-agent-java/assets/37203843/1e08eecc-cc05-4ea0-ba99-4aa776dadfce)

就能录制到body里有 但是回放还是回放为空的 应该回放也要兼容下这个 是不兼容哇 还是其他地方不支持这个类型么

**Comment by mr3** [comment]
@ZHFlys 我们确认后回复你.

**Comment by mr3** [comment]
@DanLi39 PTAL

**Comment by DanLi39** [comment]
> 如果Content-Type为form-data 参数默认录制不到 body为空 agent的CachedBodyRequestWrapperV3#isFormPost加上这个判断body
> 
> ![image](https://user-images.githubusercontent.com/37203843/278523779-1e08eecc-cc05-4ea0-ba99-4aa776dadfce.png)
> 
> 就能录制到body里有 但是回放还是回放为空的 应该回放也要兼容下这个 是不兼容哇 还是其他地方不支持这个类型么

For form input parameters in the "application/x-www-form-urlencoded" format, we write the input parameters into CachedContent based on the judgment of the isFormPost method. For data in other formats, it can be read through the inputStream in the request. And the data in requestBody can be recorded and replayed normally. You can refer to this method: io.arex.inst.httpservlet.ServletExtractor#getRequest.

**Comment by mr3** [comment]
@ZHFlys 此问题已修复，请拉取最新main代码重试。
