### ISSUE TITLE
content-type : application/ x-www-form-urlencoded录制请求会展示base64转码

### ISSUE THREAD

**Issue by q120379739** [arextest/arex-agent-java#317]
**Bug description**
content-type : application/ x-www-form-urlencoded录制请求会展示base64转码
![image](https://github.com/arextest/arex-agent-java/assets/54164039/cfe6b28a-1b09-4a2b-803c-317e199aad9b)

hat happened instead? What error message did you get?

**Environment**

Compiler: (e.g., "AdoptOpenJDK 1.8.0")
arex-agent-java: (e.g., "0.3.12")

**Comment by mr3** [comment]
@DanLi39 PTAL

**Comment by DanLi39** [comment]
> **Bug description** content-type : application/ x-www-form-urlencoded录制请求会展示base64转码 ![image](https://user-images.githubusercontent.com/54164039/280601342-cfe6b28a-1b09-4a2b-803c-317e199aad9b.png)
> 
> hat happened instead? What error message did you get?
> 
> **Environment**
> 
> Compiler: (e.g., "AdoptOpenJDK 1.8.0") arex-agent-java: (e.g., "0.3.12")

Taking into account the user's custom conversion format, unified base64 transcoding was performed during the recording process.

**Comment by DanLi39** [comment]
> **Bug description** content-type : application/ x-www-form-urlencoded录制请求会展示base64转码 ![image](https://user-images.githubusercontent.com/54164039/280601342-cfe6b28a-1b09-4a2b-803c-317e199aad9b.png)
> 
> hat happened instead? What error message did you get?
> 
> **Environment**
> 
> Compiler: (e.g., "AdoptOpenJDK 1.8.0") arex-agent-java: (e.g., "0.3.12")
