### ISSUE TITLE
jdk1.8.0_40 build  arex-agent-java error

### ISSUE THREAD

**Issue by linda0007** [arextest/arex-agent-java#32]
![e0d23c4c141043c4916069b2ef2965f](https://user-images.githubusercontent.com/20278174/182991475-55c6c315-4f30-4666-951b-54760fb41c9c.jpg)
![529e7f02ca3e899ca844ca1f445d93e](https://user-images.githubusercontent.com/20278174/182991492-ce5b0539-9170-4382-acf3-9570ef178a81.jpg)

**Comment by mengqcc** [comment]
This is a bug in some versions of the Oracle JDK， see：https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8219318

**Comment by mr3** [comment]
Fixed in PR: #33, I will close this issue. If you have any questions, please reopen it.

**Comment by linda0007** [comment]
赞
