### ISSUE TITLE
feign http请求使用的原生LoadBalancerFeignClient，需要支持原生请求的录制

### ISSUE THREAD

**Issue by China520wuli** [arextest/arex-agent-java#320]
![d6592a088448fc3e6c2da8901c7d1a3](https://github.com/arextest/arex-agent-java/assets/43128745/02562cae-de45-4e3e-9e07-1c9b0138100d)

**Comment by lucas-myx** [comment]
目前arex支持apcahe httpclinet、okhttp等，但该case使用的是feign原生的client，即jdk原生的http请求方式，这种情况下需要单独支持feign组件的录制回放（尝试配置过动态类，但某些情况下结果无法序列化）

**Comment by YongwuHe** [comment]
已支持，版本：v0.3.14，可以使用这个版本尝试一下。
