### ISSUE TITLE
redis 请求未录制

### ISSUE THREAD

**Issue by pengjm1987** [arextest/arex-agent-java#321]
![image_10](https://github.com/arextest/arex-agent-java/assets/150350491/7cc64f84-c5e1-43c2-b427-603f4576e923)
![image_9](https://github.com/arextest/arex-agent-java/assets/150350491/f27e2d7f-75c3-46bf-aa0c-445c9c5ebfc4)
使用lettuce 5.2.1版本
Redis 未录入，导致回放无法mock从而失败

**Comment by mr3** [comment]
@DanLi39 PTAL
