### ISSUE TITLE
流量录制对于 dubbo 3.2 版本不支持

### ISSUE THREAD

**Issue by YczYanchengzhe** [arextest/arex-agent-java#324]
**Is your feature request related to a problem? Please describe.**
使用版本 ： https://github.com/apache/dubbo/blob/3.2/pom.xml 
小版本号：
3.2.9 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lucas-myx** [comment]
@YczYanchengzhe 
we will verify this phenomenon first after receiving it. thank you for your feedback

**Comment by mr3** [comment]
@YczYanchengzhe 感谢反馈，Dubbo 3.2 对于 Server Context Attachment 有所调整，导致 AREX Trace 传递失败，这个问题已经在修复中了。

@DanLi39 PTAL.

**Comment by mr3** [comment]
@YczYanchengzhe This issue has been fixed in [#518]. If you have more information, please reopen and add it.

**Comment by DanLi39** [comment]
@YczYanchengzhe  This issue has been fixed. Please pull the latest code to try.
