### ISSUE TITLE
回放计划状态FAIL_INTERRUPTED，回放case状态Queued，agent日志显示接口用到的一个query回放时反序列化类型错误

### ISSUE THREAD

**Issue by MaxZhou117** [arextest/arex-agent-java#381]
**Bug description**

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

Please provide [GitHub address] to reproduce this issue.

**Expected behavior**

What should happen? / What did you expect?

**What went wrong?**
What happened instead? What error message did you get?
接口录制的query Response：
[{
  "LineFavoritesID": 1192037923441082400,
  "LastModifyUserName": null,
  "FavoritesType": 1,
  "LastModifyUserID": null,
  "LineID": 1167354935260479500,
  "LastModifyDate": null,
  "UserID": 1186136861303636000,
  "CreateUserID": 1186136861303636000,
  "CreateUserName": null,
  "CreateDate": "2024-01-03 17:33:08.000",
  "delflag": false
}]
agent报错日志：
<img width="1270" alt="image" src="https://github.com/arextest/arex-agent-java/assets/75799713/571f6b66-2d2c-4c5d-97ac-97e8cbf2b1d0">

**Environment**

Compiler: (e.g., "AdoptOpenJDK 1.8.0")
arex-agent-java: (e.g., "0.2.0")

**Additional context**
If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by lucas-myx** [comment]
@MaxZhou117 请更新到最新的agent版本，再重新录制回放验证

**Comment by mr3** [comment]
@MaxZhou117 This issue will be closed. If you have more infomation, please reopen and add it.
