### ISSUE TITLE
was应用挂载agent无法启动

### ISSUE THREAD

**Issue by importzhh** [arextest/arex-agent-java#386]
**Bug description**
agent打印了success日志
<img width="1464" alt="success" src="https://github.com/arextest/arex-agent-java/assets/40499441/e10da07f-5c7f-4f8d-bccb-a13656b075b9">
转换类的过程提示有类似下面的报错
<img width="1469" alt="error" src="https://github.com/arextest/arex-agent-java/assets/40499441/3c7289d8-a3f5-4e51-a580-89005dbbf996">
was应用加上skywalking(https://github.com/apache/skywalking), jvmsandbox repeater (https://github.com/alibaba/jvm-sandbox-repeater) 启动整体耗时在4-5分钟左右,加上arexagent后无法启动,was进程hang住,此时的日志显示一直在执行io.arex.inst.extension.matcher.SafeExtendsClassMatcher#matches(net.bytebuddy.description.type.TypeDescription) 这个方法
<img width="1405" alt="iShot_2024-01-24_21 31 15" src="https://github.com/arextest/arex-agent-java/assets/40499441/0bc8eee9-e459-4721-9da6-68845d8b3716">
was应用去掉arexagent正常启动后用arthas统计类信息如下
![classloader](https://github.com/arextest/arex-agent-java/assets/40499441/489904d7-ca28-4b66-92e8-987ab407254b)

**Comment by lucas-myx** [comment]
@importzhh 这种现象现在还有吗？试试更新到最新的agent版本验证下，有问题随时反馈

**Comment by mr3** [comment]
@importzhh This issue will be closed. If you have more infomation, please reopen and add it.
