### ISSUE TITLE
redis操作未被识别mock掉,回放仍然执行了redis操作(spring-data-redis-2.2.4.RELEASE)

### ISSUE THREAD

**Issue by HumorChen** [arextest/arex-agent-java#398]
redis操作未被识别mock掉,回放仍然执行了redis操作(spring-data-redis-2.2.4.RELEASE)

![image-20240202093133310](https://chpic.oss-cn-shanghai.aliyuncs.com/202402020931500.png)
定义了一个redis写入接口
![image-20240202093344997](https://chpic.oss-cn-shanghai.aliyuncs.com/202402020933710.png)
然后我请求了这个接口，录制到了请求
![image-20240202093248721](https://chpic.oss-cn-shanghai.aliyuncs.com/202402020932903.png)
我手动操作去redis删除这个写入的key，然后执行回放，回放完成后，通过了检查，我去redis看，key被设置上了。在回放样例详情页面也没有看到arex识别到这个redis写入操作。（在支持群已反馈，建issue备忘 ）
![image-20240202093947745](https://chpic.oss-cn-shanghai.aliyuncs.com/202402020939958.png)

**Comment by HumorChen** [comment]
redisson-spring-data-25-3.16.1
redisson 3.16.1

**Comment by lucas-myx** [comment]
spring-data-redis如果指定的是redisson客户端的话，内部使用的是redisson的`commandExecutor.writeAsync/readAsync`方式，arex修饰的是另外的方法，这个我们调整下，兼容spring的方式，感谢反馈

**Comment by mr3** [comment]
@HumorChen Thank you for posting in the AREX community! This issue has been fixed in #433. If you have more infomation, please reopen and add it.
