### ISSUE TITLE
MybatisPlus 自动生成的ID（ID_WORKER类型）未mock

### ISSUE THREAD

**Issue by HumorChen** [arextest/arex-agent-java#399]
MybatisPlus 自动生成的ID（ID_WORKER类型）未mock，自增ID看到mock了
回放的时候，如果这个mysql 数据库插入操作，实体对象的ID是个@TableId(type = IdType.ID_WORKER_STR)，这个ID是全局唯一长整数，mybatis-plus自动生成的，那在回放的时候这个ID没有被回放，变成了null

replay case ->record detail里能看到这个插入操作被识别到了，回放的时候这个自动生成的ID没了
```java
@TableId(type = IdType.ID_WORKER_STR)
private String id;
```
样例值：1752142321874501633

 ![image-20240202094738522](https://chpic.oss-cn-shanghai.aliyuncs.com/202402020948444.png)

代码
建了一个实体对象，保存到数据库了，这个实体对象的ID是自动生成的@TableId(type = IdType.ID_WORKER_STR)
 ![image-20240202095002277](https://chpic.oss-cn-shanghai.aliyuncs.com/202402020950526.png)

日志

![image-20240202095135854](https://chpic.oss-cn-shanghai.aliyuncs.com/202402020951232.png)
实体类
![image-20240202095234060](https://chpic.oss-cn-shanghai.aliyuncs.com/202402020952641.png)

**Comment by mr3** [comment]
Thank you for posting in the AREX community! This issue has been fixed in PR: #404. If you have more infomation, please reopen and add it.
