### ISSUE TITLE
注入被测服务，启动服务时，提示nested exception is java.lang.NoClassDefFoundError: io/arex/inst/httpclient/common/HttpClientAdapter

### ISSUE THREAD

**Issue by liaolongfei** [arextest/arex-agent-java#41]
![image](https://user-images.githubusercontent.com/6407371/185276535-7f369e6a-dc29-4ffd-8331-353bc71998f3.png)

**Comment by mr3** [comment]
Fixed in PR: #40 , I will close this issue. If you have any questions, please reopen it.
