### ISSUE TITLE
并发场景支持

### ISSUE THREAD

**Issue by DeepLJH0001** [arextest/arex-agent-java#414]
我们业务场景接口执行存在大量并发和重复的任务，比如多个线程池，并发取随机数，并根据随机数选择分支执行。回放的时候arex可以支持正确的随机数回放到正确的线程池的线程中么？

**Comment by lucas-myx** [comment]
支持，并发或异步的场景都支持，随机数的话可以配置动态类方法解决（即录制的随机数和回放环境时保持一致，就能保证回放的分支和录制时一致），但有一点需要确认，你说的任务是job那种定时任务类型吗？arex录制回放的前提是基于spring web、java servlet、dubbo、netty这些组件。

**Comment by DeepLJH0001** [comment]
> 支持，并发或异步的场景都支持，随机数的话可以配置动态类方法解决（即录制的随机数和回放环境时保持一致，就能保证回放的分支和录制时一致），但有一点需要确认，你说的任务是job那种定时任务类型吗？arex录制回放的前提是基于spring web、java servlet、dubbo、netty这些组件。

就是复杂的异步场景，配置动态类方法是如何把MockResult正确匹配到异步线程中，让录制的随机数和回放环境时保持一致呢，因为每个异步线程的执行逻辑可能存在非幂等

**Comment by DeepLJH0001** [comment]
感谢大佬，看到相应代码了，应该是这里把 https://github.com/arextest/arex-agent-java/blob/main/arex-instrumentation-api/src/main/java/io/arex/inst/runtime/match/ReplayMatcher.java#L30

**Comment by lucas-myx** [comment]
欢迎试用
