### ISSUE TITLE
动态类因为SpringCGLIB代理 录制了但是回放无法使用从而回放失败

### ISSUE THREAD

**Issue by ZHFlys** [arextest/arex-agent-java#437]
**Bug description**
动态类配置后录制成功 最新版入库到节点arex.mergeRecord节点 ， 但是回放时 先从库将节点序列化成cachedReplayResultMap对象 key是请求api计算的 按照当时录制的方法签名计算的hash  但是取key数据时 通过 MockUtils.methodRequestTypeHash计算的方法签名 包含$$EnhancerBySpringCGLIB$$random$$的序列 导致无法从合并map取出来 这块逻辑应该兼容下 我的临时办法是agent这边重新计算hash 是正则去掉这个后的 如 operationName.replaceAll("\\$\\$EnhancerBySpringCGLIB\\$\\$[a-zA-Z0-9]+", "")

**Steps to reproduce**
在动态类配置后重启录制 然后回放

**Expected behavior**

在动态节点arex.mergeRecord录制成功入库并且界面能查询到 回放相应也应该成功

**What went wrong?**
回放错误 查询动态mock数据为null 导致回放失败

**Environment**

arex-agent-java: 0.4.2

**Additional context**

**Comment by mr3** [comment]
@ZHFlys 感谢反馈，方便贴一下录制下来的数据吗？

**Comment by ZHFlys** [comment]
![image](https://github.com/arextest/arex-agent-java/assets/37203843/fb61aa8e-426b-46fc-8096-20192b31ef17)
类似这样的命名 现在我替换后 入库和查询都正则了这个 暂时没问题

**Comment by mr3** [comment]
@ZHFlys 感谢回复，你可以提交一个PR修复这个问题。

**Comment by DanLi39** [comment]
> ![image](https://private-user-images.githubusercontent.com/37203843/323043476-03d2a860-a080-491e-9fc6-dc40904be947.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTMyOTAsIm5iZiI6MTcxNDI5Mjk5MCwicGF0aCI6Ii8zNzIwMzg0My8zMjMwNDM0NzYtMDNkMmE4NjAtYTA4MC00OTFlLTlmYzYtZGM0MDkwNGJlOTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA4Mjk1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMjY0N2VlMjE4MmU0ODBlNzhmOWRhOGExODQ5ZDY3ODkzNTdhNmY1OTM5MDJmODI2MGNkMWZmOGM0MDViNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YxTbEyUotnGnNEuxsOm0r_0xbllLMs7V7irBot3z6tw)
> 
> 类似这样的命名 现在我替换后 入库和查询都正则了这个 暂时没问题

@ZHFlys This issue has been fixed. The latest code of the main branch can be pulled and used.
