### ISSUE TITLE
[Bug] http外部调用没有被录制到

### ISSUE THREAD

**Issue by zengyixun** [arextest/arex-agent-java#447]
### Search before asking

- [X] I have searched the existing [issues](https://github.com/arextest/arex-agent-java/issues) before asking.

### AREX Test Service

AREX Java Agent (arextest/arex-agent-java)

### Current Behavior

private final CloseableHttpClient newRiskHttpClient = HttpClients.createMinimal();
String result = newRiskHttpClient.execute(post, handler);
这个http调用没有录到数据

### Expected Behavior

newRiskHttpClient.execute(post, handler)和result结果被录制下来

### Steps To Reproduce

1. 版本org.apache.httpcomponents.httpclient:4.5.2
2. 在class中定义private final CloseableHttpClient newRiskHttpClient = HttpClients.createMinimal();
3. HttpPost post = new HttpPost(zeldaGateway + "/aaa");
            BasicResponseHandler handler = new BasicResponseHandler();
            ZeldaRequest request = genZztRiskRequest(token, user, feature, appid);
            if (ConstentParam.BAOHE_APPID.equalsIgnoreCase(appid)) {
                request.setEvent(ConstentParam.BAOHE_LOGIN);
            }
            buildRequest(post, request);
String result = newRiskHttpClient.execute(post, handler);
4.执行到newRiskHttpClient.execute，但没有被录制

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

**Comment by mr3** [comment]
@zengyixun Thank you for posting in the AREX community! This issue has been fixed in #446. If you have more infomation, please reopen and add it.
