### ISSUE TITLE
[Bug] 反序列化时 null数据也会调用set方法

### ISSUE THREAD

**Issue by ZHFlys** [arextest/arex-agent-java#448]
### Search before asking

- [X] I have searched the existing [issues](https://github.com/arextest/arex-agent-java/issues) before asking.

### AREX Test Service

AREX Java Agent (arextest/arex-agent-java)

### Current Behavior

入库时的属性为null 反序列时被set方法重新设置 导致回放失败 

### Expected Behavior

没设置的属性为null 序列化时不应该去调用set方法 set方法可能会影响反序列化其他属性 导致值不一致

### Steps To Reproduce

类A属性 定义时 int a=1  int b  setB(){a=2;} 反序列化时 默认的a=1没序列上 被2覆盖

### Anything else

是不是主要更改 io.arex.foundation.serializer.jackson.JacksonSerializer#configMapper 方法

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

**Comment by mr3** [comment]
@ZHFlys This issue will be closed. If you have more infomation, please reopen and add it.
