### ISSUE TITLE
SimpleAsyncTaskExecutor is not supported

### ISSUE THREAD

**Issue by harvey-xu1981** [arextest/arex-agent-java#449]
### Search before asking

- [X] I have searched the existing [issues](https://github.com/arextest/arex-agent-java/issues) before asking.

### AREX Test Service

AREX Java Agent (arextest/arex-agent-java)

### Current Behavior

SimpleAsyncTaskExecutor is not supported

### Expected Behavior

@Async
public void test() {
...
}
Fail to record

### Steps To Reproduce

@Async
public void test() {
...
}
Fail to record

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

**Comment by mr3** [comment]
@harvey-xu1981 Thank you for posting in the AREX community! 

After communicating and testing to confirm that `SimpleAsyncTaskExecutor` is supported. 

This issue will be closed. If you have more infomation, please reopen and add it.
