### ISSUE TITLE
mongoTemplate.insert无法录制及回放

### ISSUE THREAD

**Issue by claywong** [arextest/arex-agent-java#462]
### Search before asking

- [X] I have searched the existing [issues](https://github.com/arextest/arex-agent-java/issues) before asking.

### AREX Test Service

AREX Java Agent (arextest/arex-agent-java)

### Current Behavior

`PInfoPure pure = mongoTemplate.insert(pInfoPure);
pInfoPure.setId(pure.getId());`
这样的方法中，insert没有录制和回放

![image](https://github.com/arextest/arex-agent-java/assets/222770/fe91c403-0d66-473d-a5d2-6aed2635ed82)

![image](https://github.com/arextest/arex-agent-java/assets/222770/3acbef46-9d3b-4f60-a26d-ce28ffa79adb)

![image](https://github.com/arextest/arex-agent-java/assets/222770/713ecfe3-028f-454a-a87a-e55b465d63d7)

回放错误现象为pure对象的id属性未被设置
![image](https://github.com/arextest/arex-agent-java/assets/222770/b076a3dc-730e-4c30-81d5-df02138257d5)

### Expected Behavior

我将org.springframework.data.mongodb.core.MongoTemplate.insert设置为动态类后，录制和回放正常

### Steps To Reproduce

spring-data-mongo 2.1.9
mongodb-driver3.8.2

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

**Comment by YongwuHe** [comment]
fix: #469
