### ISSUE TITLE
[Feature] 支持lettuce 6.0——6.1版本的修改内容

### ISSUE THREAD

**Issue by hulahulaoye** [arextest/arex-agent-java#472]
### Is there an existing issue for this?

- [X] I had searched in the [issues](https://github.com/arextest/arex-agent-java/issues) and found no similar issues.

### Description

试用中发现服务使用lettuce6.0.8版本录制会报错，所以修改对应版本范围后功能正常
1. 
![image](https://github.com/arextest/arex-agent-java/assets/75613379/98bff92d-7949-4179-a94e-77e24a6d9d53)
2. 
![image](https://github.com/arextest/arex-agent-java/assets/75613379/9ce0822c-3507-49d2-8126-7df1be954b70)

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

**Comment by DanLi39** [comment]
@hulahulaoye This issue has been resolved, please pull the latest branch to use.
