### ISSUE TITLE
[Feature] 支持openFeign

### ISSUE THREAD

**Issue by dongann** [arextest/arex-agent-java#492]
### Is there an existing issue for this?

- [X] I had searched in the [issues](https://github.com/arextest/arex-agent-java/issues) and found no similar issues.

### Description

本平台能否支持下 openfeign呀，openfeign版本3.1.4

### Solution

本平台能否支持下 openfeign呀，openfeign版本3.1.4

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

**Comment by 496767099** [comment]
本平台能否支持下 openfeign呀，openfeign版本3.1.3.  已在微信群中沟通openfeign版本3.1.3发现现在并不支持

**Comment by 496767099** [comment]
本平台能否支持下 spring cloud的FeignClient呀，FeignClient版本3.1.3. 已在微信群中沟通FeignClient版本3.1.3发现现在并不支持

**Comment by mr3** [comment]
@dongann @496767099 感谢你们在 AREX 社区反馈，我们会尽快确认支持。

**Comment by mr3** [comment]
## 20240625 Openfeign Component Review

### version: [3.1.3,4.1.2], Record/Replay Success

```xml
  <parent>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-dependencies-parent</artifactId>
    <version>[3.1.3,4.1.2]</version>
    <relativePath></relativePath>
  </parent>
  <version>[3.1.3,4.1.2]</version>
  <dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-openfeign-core</artifactId>
    <version>${project.version}</version>
  </dependency>
  <dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-openfeign</artifactId>
    <version>${project.version}</version>
  </dependency>
```

## Spring Cloud Replease Notes
- https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2021.0-Release-Notes
- https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-2023.0-Release-Notes

**Comment by mr3** [comment]
@dongann @496767099 The above is a summary of my tests, please provide more information.

**Comment by mr3** [comment]
## 20240626 Openfeign Component Review

### version: 2.2.9.RELEASE, Record/Replay Success

```xml
  <parent>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-dependencies-parent</artifactId>
    <version>2.3.5.RELEASE</version>
    <relativePath></relativePath>
  </parent>
  <version>2.2.9.RELEASE</version>
  <dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-openfeign-core</artifactId>
    <version>${project.version}</version>
  </dependency>
  <dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-openfeign</artifactId>
    <version>${project.version}</version>
  </dependency>
```

## Spring Cloud Replease Notes
- https://github.com/spring-cloud/spring-cloud-release/wiki/Spring-Cloud-Hoxton-Release-Notes
- https://spring.io/projects/spring-cloud

**Comment by mr3** [comment]
@dongann @496767099 This issue will be closed. If you have more information, please reopen and add it.
