### ISSUE TITLE
[Bug] ES查询录制后返回值无法再次解析

### ISSUE THREAD

**Issue by 496767099** [arextest/arex-agent-java#507]
### Search before asking

- [X] I have searched the existing [issues](https://github.com/arextest/arex-agent-java/issues) before asking.

### AREX Test Service

AREX Java Agent (arextest/arex-agent-java)

### Current Behavior

我在流量录制的时候调用ES查询，response你们有做什么改动吗？解析失败了。去掉流量录制的那台机器一直是正常的
![caa06a787fb01e9522991a2ad2cb599d](https://github.com/arextest/arex-agent-java/assets/30050783/1eed1882-6c73-4cda-b591-ac7f577ad06a)

### Expected Behavior

我在流量录制的时候调用ES查询，response你们有做什么改动吗？解析失败了。去掉流量录制的那台机器一直是正常的

### Steps To Reproduce

arex-agent-java 0.4.6 版本
Es是阿里云7.10.0版本
![3f4aa507a507db1c4994db19c71295c3](https://github.com/arextest/arex-agent-java/assets/30050783/1ee97a83-e929-46da-8334-fc8304127f38)
![49a85af8158800910212845b11e82c19](https://github.com/arextest/arex-agent-java/assets/30050783/200feb60-73f4-401b-887f-a6f95e2c5dfd)
![3604eb93611dacfb9458c0954d737c8f](https://github.com/arextest/arex-agent-java/assets/30050783/9acadce0-df8e-4ff8-839f-b9f8dfd3a271)

### Anything else

我在流量录制的时候调用ES查询，response你们有做什么改动吗？解析失败了。去掉流量录制的那台机器一直是正常的

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

**Comment by mr3** [comment]
@496767099 感谢您在AREX社区反馈，我们会尽快确认修复此问题，请持续关注此issue。

**Comment by mr3** [comment]
@496767099 我使用7.15.2版本挂载Agent测试下来是可以正常录制，业务也可以正常解析的。明天有时间麻烦请一起看看
```xml
<dependency>
    <groupId>org.elasticsearch.client</groupId>
    <artifactId>elasticsearch-rest-high-level-client</artifactId>
    <version>7.15.2</version>
</dependency>
```

**Comment by mr3** [comment]
最新同步：视频会议确认，ES功能录制和回放正常，不影响业务应用正常解析。等后续 @496767099 发现后再反馈。

**Comment by 496767099** [comment]
排查后发现在流量录制的时候是没问题的,在流量回放的时候因为缓存失效走了ES查询链路.并且请求参数缺失导致了查询结果解析失败.  并非AREX问题
