### ISSUE TITLE
restful url path can not be limited

### ISSUE THREAD

**Issue by abstinencetang** [arextest/arex-agent-java#525]
### Search before asking

- [X] I have searched the existing [issues](https://github.com/arextest/arex-agent-java/issues) before asking.

### AREX Test Service

AREX Java Agent (arextest/arex-agent-java)

### Current Behavior

restful url path can not be limted, for example @Mapping("test/{name}/{age}"), if name and age is different, they use different limiter, so can't be limted

### Expected Behavior

@Mapping("test/{name}/{age}"), if name and age is different, they use different limiter, so can't be limted. expect they can be limted by "test/{name}/{age}", not their real value.

### Steps To Reproduce

...

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

**Comment by Totti0135** [comment]
The "exclusion" setting has the same problem.

**Comment by lucas-myx** [comment]
@Totti0135 
exclusion set `test/{name}/{age}` url

**Comment by abstinencetang** [comment]
low version springboot can't work yet，for example springboot 2.1.6-RELEASE
