### ISSUE TITLE
[Feature] agent打印的日志目前是输出在应用中，建议不要输出到应用日志中

### ISSUE THREAD

**Issue by lydqc** [arextest/arex-agent-java#544]
### Is there an existing issue for this?

- [X] I had searched in the [issues](https://github.com/arextest/arex-agent-java/issues) and found no similar issues.

### Are you willing to submit a pull request to implement this on your own?

- [ ] Yes I am willing to submit a pull request on my own!

**Comment by mr3** [comment]
@lydqc supports writing agent log to specified path by setting the property `-Darex.log.path=/var/tmp/logs/`, if not set, the default directory where the agent jar is located will be used.

**Comment by claywong** [comment]
这个特性带来的优势是什么呢？
日志采集还需要额外配置一个日志路径

**Comment by lucas-myx** [comment]
主要是为了和原有的业务日志区分开，不干扰业务日志的正常使用，也便于arex后面做agent日志方面的扩展，比如更方便的展示录制回放的相关信息，便于用户快速排查，如果没有设置日志路径默认是agent jar所在目录
